---
apiVersion: v2
name: ldap-server
description: OpenLDAP server with slapd.conf-based configuration
type: application
version: 0.1.0
appVersion: 2.4.58
dependencies:
  - name: nubus-common
    version: 0.29.13
    repository: oci://artifacts.software-univention.de/nubus/charts
...
