---
slapdConf:
  existingConfigMap: null
  content: null
  file: files/slapd.conf

ldapServer:
  config:
    ldapBaseDn: dc=example,dc=org
    logLevel: stats

  auth:
    password: admin
    existingSecret: null

  image:
    repository: gitregistry.knut.univention.de/univention/customers/dataport/upx/container-ldap/ldap-server
    tag: latest
    pullPolicy: IfNotPresent

  resources: {}

ldapManager:
  image:
    repository: gitregistry.knut.univention.de/univention/customers/dataport/upx/container-ldap/ldap-manager
    tag: latest
    pullPolicy: IfNotPresent

  resources: {}

persistence:
  enabled: true
  size: 1Gi
  storageClass: null

service:
  type: ClusterIP
  ports:
    ldap: 389

seedData:
  existingConfigMap: null
  content: null
  file: ""

additionalAnnotations: {}
additionalLabels: {}
fullnameOverride: null
nameOverride: null
nodeSelector: {}
tolerations: []
topologySpreadConstraints: []
...
