sonar.projectKey=Y0-L0_ldap-server-helm
sonar.organization=y0-l0

sonar.sources=ldap-manager
sonar.exclusions=ldap-manager/**/*_test.go,ldap-manager/test/**
sonar.tests=ldap-manager
sonar.test.inclusions=ldap-manager/**/*_test.go

sonar.go.coverage.reportPaths=ldap-manager/coverage.out
