{{ if not .Values.slapdConf.existingConfigMap }}
---
{
  apiVersion: "v1",
  kind: "ConfigMap",
  metadata: {
    name: {{ printf "%s-slapd-conf" (include "common.names.fullname" .) | quote }},
    labels: {{ include "common.labels.standard" (dict "customLabels" .Values.additionalLabels "context" $) | fromYaml | toJson }},
    {{ if .Values.additionalAnnotations }}
    annotations: {{ .Values.additionalAnnotations | toJson }},
    {{ end }}
  },
  data: {
    slapd.conf: {{ tpl (coalesce .Values.slapdConf.content (.Files.Get .Values.slapdConf.file)) . | quote }},
  },
}
{{ end }}
