{{ if not .Values.slapdConf.existingConfigMap }}
---
{
  apiVersion: "v1",
  kind: "ConfigMap",
  metadata: {
    name: {{ printf "%s-slapd-conf" (coalesce .Values.fullnameOverride .Release.Name) | quote }},
    labels: {
      app.kubernetes.io/name: {{ coalesce .Values.nameOverride .Chart.Name | quote }},
      app.kubernetes.io/instance: {{ .Release.Name | quote }},
      app.kubernetes.io/version: {{ .Chart.AppVersion | quote }},
      app.kubernetes.io/managed-by: {{ .Release.Service | quote }},
    },
    {{ if .Values.additionalAnnotations }}
    annotations: {{ .Values.additionalAnnotations | toJson }},
    {{ end }}
  },
  data: {
    slapd.conf: {{ tpl (coalesce .Values.slapdConf.content (.Files.Get .Values.slapdConf.file)) . | quote }},
  },
}
{{ end }}
