{{ if not .Values.seedData.existingConfigMap }}
{{ if or .Values.seedData.content .Values.seedData.file }}
---
{
  apiVersion: "v1",
  kind: "ConfigMap",
  metadata: {
    name: {{ printf "%s-seed-ldif" .Release.Name | quote }},
    labels: {
      app.kubernetes.io/name: {{ .Chart.Name | quote }},
      app.kubernetes.io/instance: {{ .Release.Name | quote }},
      app.kubernetes.io/version: {{ .Chart.AppVersion | quote }},
      app.kubernetes.io/managed-by: {{ .Release.Service | quote }},
    },
  },
  data: {
    seed.ldif: {{ tpl (coalesce .Values.seedData.content (.Files.Get .Values.seedData.file)) . | quote }},
  },
}
{{ end }}
{{ end }}
