{{ if not .Values.ldapServer.auth.existingSecret }}
---
{
  apiVersion: "v1",
  kind: "Secret",
  metadata: {
    name: {{ printf "%s-admin" (coalesce .Values.fullnameOverride .Release.Name) | quote }},
    labels: {
      app.kubernetes.io/name: {{ coalesce .Values.nameOverride .Chart.Name | quote }},
      app.kubernetes.io/instance: {{ .Release.Name | quote }},
      app.kubernetes.io/version: {{ .Chart.AppVersion | quote }},
      app.kubernetes.io/managed-by: {{ .Release.Service | quote }},
    },
    {{ if .Values.additionalAnnotations }}
    annotations: {{ .Values.additionalAnnotations | toJson }},
    {{ end }}
  },
  type: "Opaque",
  stringData: {
    password: {{ .Values.ldapServer.auth.password | quote }},
  },
}
{{ end }}
