{{ if not .Values.ldapServer.auth.existingSecret.name }}
---
{
  apiVersion: "v1",
  kind: "Secret",
  metadata: {
    name: {{ include "nubus-common.secrets.name" (dict "defaultNameSuffix" "admin" "context" .) | quote }},
    labels: {{ include "common.labels.standard" (dict "customLabels" .Values.additionalLabels "context" $) | fromYaml | toJson }},
    {{ if .Values.additionalAnnotations }}
    annotations: {{ .Values.additionalAnnotations | toJson }},
    {{ end }}
  },
  type: "Opaque",
  stringData: {
    password: {{ .Values.ldapServer.auth.password | quote }},
  },
}
{{ end }}
