{{ if not .Values.ldapServer.auth.existingSecret }}
---
{
  apiVersion: "v1",
  kind: "Secret",
  metadata: {
    name: {{ printf "%s-admin" .Release.Name | quote }},
    labels: {
      app.kubernetes.io/name: {{ .Chart.Name | quote }},
      app.kubernetes.io/instance: {{ .Release.Name | quote }},
      app.kubernetes.io/version: {{ .Chart.AppVersion | quote }},
      app.kubernetes.io/managed-by: {{ .Release.Service | quote }},
    },
  },
  type: "Opaque",
  stringData: {
    password: {{ .Values.ldapServer.auth.password | quote }},
  },
}
{{ end }}
