---
{
  apiVersion: "v1",
  kind: "Service",
  metadata: {
    name: {{ .Release.Name | quote }},
    labels: {
      app.kubernetes.io/name: {{ .Chart.Name | quote }},
      app.kubernetes.io/instance: {{ .Release.Name | quote }},
      app.kubernetes.io/version: {{ .Chart.AppVersion | quote }},
      app.kubernetes.io/managed-by: {{ .Release.Service | quote }},
    },
  },
  spec: {
    type: {{ .Values.service.type | quote }},
    selector: {
      app.kubernetes.io/name: {{ .Chart.Name | quote }},
      app.kubernetes.io/instance: {{ .Release.Name | quote }},
    },
    ports: [{
      name: "ldap",
      port: {{ .Values.service.ports.ldap }},
      targetPort: "ldap",
      protocol: "TCP",
    }],
  },
}
