---
{
  apiVersion: "v1",
  kind: "Service",
  metadata: {
    name: {{ include "common.names.fullname" . | quote }},
    labels: {{ include "common.labels.standard" (dict "customLabels" .Values.additionalLabels "context" $) | fromYaml | toJson }},
    {{ if .Values.additionalAnnotations }}
    annotations: {{ .Values.additionalAnnotations | toJson }},
    {{ end }}
  },
  spec: {
    type: {{ .Values.service.type | quote }},
    selector: {{ include "common.labels.matchLabels" (dict "customLabels" .Values.additionalLabels "context" $) | fromYaml | toJson }},
    ports: [{
      name: "ldap",
      port: {{ .Values.service.ports.ldap }},
      targetPort: "ldap",
      protocol: "TCP",
    }],
  },
}
